### ISSUE TITLE
Touch remaps force combos in PS4 Link

### ISSUE THREAD

**Issue by RitschiRitsch** [MERLev/remaPSV2#10]
If I remap rear or front touch, in PS4 Link it triggers both buttons: the one foreseen by the app and the remapped one. Or is it because of circular reference?
My remaps are as follows:
L1 -> LT/L2
R1 -> RT/R2
Rear Touch TopLeft -> L1
Rear Touch TopRight -> R1

When in-game with PS4 Link, e.g. Rear Touch TopLeft triggers L1 but as well LT/L2 at the same time when touched.

**Comment by MERLev** [comment]
Those issues should be fixed in reVita
