### ISSUE TITLE
Bug -analogs

### ISSUE THREAD

**Issue by Kaiiela** [MERLev/remaPSV2#14]
Enso 3.60
Spelunky -PCSC00288

Diagonals on left analog are ignored and do not function when this plugin is enabled. ( many different tests performed and with original settings )
This is the only game I’ve found with this issue so far.

This is a terrific plugin btw!

**Comment by MERLev** [comment]
Thanks for the report. 
I could provide you with test build, so you could test if it is fixed there.
If you are interested, you can contact me on Discord, "Mer1e@4678"

**Comment by MERLev** [comment]
Should be fixed in reVita in 1.0.4 update
