### ISSUE TITLE
Playing Hatsune Miku Project diva f

### ISSUE THREAD

**Issue by dkrmdi** [MERLev/remaPSV2#9]
There is still some input delay.

I still cannot use the analog sticks to play the scratch notes. I hope touch screen flick feature will be implemented some day.

**Comment by MERLev** [comment]
Can you pls describe vita model and if external controller is used? Delay issue in Diva titles was actually fixed long before public release, so it's somewhat strange. I'll check it out. Also, how much of a what delay exactly ? Some milliseconds, or seconds?
Flicks/swipes could be added in the future, but after I'll finish porting it to kernel.

**Comment by dkrmdi** [comment]
I am using vita 2000. I think I was using DS4 with the ds4vita with the analog stick improvements release. I just played with vita's physical button today, and I had no delay. I'll give you an update again after I test play with the ds4vita and udcd_uvc.

**Comment by MERLev** [comment]
Fixed in reVita.

**Comment by dkrmdi** [comment]
It now works flawlessly.
